version: "3.7"
services:
  postgres:
    image: docker.io/bitnami/postgresql:11
    volumes:
      - ./db/crawler_output.sql:/docker-entrypoint-initdb.d/crawler_output.sql
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_DATABASE=websites_database
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_PASSWORD=distribuidos
    ports:
      - "9091:5432"
  redis:
    container_name: redis
    image: redis:6.2.6
    restart: always
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command:
      [
        "redis-server",
        "--bind",
        "redis",
        "--maxmemory 2mb",
        "--maxmemory-policy allkeys-lru"
      ]
    # redis2:
    #   container_name: redis2
    #   image: redis:6.2.6
    #   restart: always
    #   ports:
    #     - "6379:6379"
    #   environment:
    #     - ALLOW_EMPTY_PASSWORD=yes
    #   command:
    #     [
    #       "redis-server",
    #       "--bind",
    #       "redis",
    #       "--maxmemory 2mb",
    #       "--maxmemory-policy allkeys-lru"
    #     ]
    # redis3:
    #   container_name: redis3
    #   image: redis:6.2.6
    #   restart: always
    #   ports:
    #     - "6379:6379"
    #   environment:
    #     - ALLOW_EMPTY_PASSWORD=yes
    #   command:
    #     [
    #       "redis-server",
    #       "--bind",
    #       "redis",
    #       "--maxmemory 2mb",
    #       "--maxmemory-policy allkeys-lru"
    #     ]